### ISSUE TITLE
Version 1.1 Roadmap

### ISSUE THREAD

**Issue by matthew-e-brown** [matthew-e-brown/download-box#3]
## Features

There are a couple of changes I would like to make for v1.1 that would make the extension a little nicer.

- [ ] Show a count of currently in-progress items
- [x] Show download speeds; not exposed by `chrome.downloads` API, would have to compute it ourselves. 
- [ ] A "show-all" button, which links to `chrome://downloads`
- [x] #2 
    - [x] Should probably also show some indication that something's been copied when you click on the button.
- [ ] A "dirty" indicator; Chrome's `downloads.search` doesn't seem to update with fresh downloads until after the extension is closed and re-opens. A little orange dot in one of the top corners could show that there are new downloads not visible.

Some other _potential_ ideas I have are:

- Showing the "in-progress" downloads in another section, separate to the completed ones. Potentially with another paginated list stacked on top of the main one. Could maybe show it only when all in-progress downloads don't appear on the first page. Only thing I'm worried about is how tall that might make the popup. Will have to tinker in Figma.

## Bug Fixes

- [x] #4
- [x] #5
